function varargout=call(h,hdl)

global zmiana_par 
global par start
global pathes

if any (h==[hdl.e_Kv hdl.e_Kf ...
            hdl.e_f1 hdl.e_f2 hdl.e_k ...
            hdl.e_gamma hdl.e_beta hdl.e_da ...
            hdl.e_thetaH hdl.e_delta1 hdl.e_delta2 ...
            hdl.e_tauk hdl.e_krok])
    par=struct('Kv',str2num(get(hdl.e_Kv,'string')),...
               'Kf',str2num(get(hdl.e_Kf,'string')),...
               'f',[str2num(get(hdl.e_f1,'string')) ...
               str2num(get(hdl.e_f2,'string'))],...
               'k',str2num(get(hdl.e_k,'string')),...
               'gamma',str2num(get(hdl.e_gamma,'string')),...
               'beta',str2num(get(hdl.e_beta,'string')),...
               'da',str2num(get(hdl.e_da,'string')),...
               'thetaH',str2num(get(hdl.e_thetaH,'string')),...
               'tauk',str2num(get(hdl.e_tauk,'string')),...
               'krok',str2num(get(hdl.e_krok,'string')),...
               'delta',[str2num(get(hdl.e_delta1,'string')) ...
               str2num(get(hdl.e_delta2,'string'))])
    par.sigma(1)=par.Kv*(1-par.f(1)*par.f(2))/(par.Kf+par.f(2)*(1-par.Kf))
    par.sigma(2)=(1-par.Kv)*(1-par.f(1)*par.f(2))/((1-par.Kf)+par.f(1)*par.Kf)
    par.k=(1-par.Kf+par.f(1)*par.Kf)/(par.Kf+par.f(2)-par.Kf*par.f(2))
    
    set(hdl.e_Kv,'string',num2str(par.Kv))
    set(hdl.e_Kf,'string',num2str(par.Kf))
    set(hdl.e_f1,'string',num2str(par.f(1)))
    set(hdl.e_f2,'string',num2str(par.f(2)))
    set(hdl.e_k,'string',num2str(par.k))
    set(hdl.e_gamma,'string',num2str(par.gamma))
    set(hdl.e_beta,'string',num2str(par.beta))
    set(hdl.e_da,'string',num2str(par.da))
    set(hdl.e_thetaH,'string',num2str(par.thetaH))
    set(hdl.e_delta1,'string',num2str(par.delta(1)))
    set(hdl.e_delta2,'string',num2str(par.delta(2)))
    set(hdl.e_sigma1,'string',num2str(par.sigma(1)))
    set(hdl.e_sigma2,'string',num2str(par.sigma(2)))
    set(hdl.e_tauk,'string',num2str(par.tauk))
    set(hdl.e_krok,'string',num2str(par.krok))
    
end
if any (h==[hdl.e_alfa10 hdl.e_alfa20 ...
            hdl.e_theta10 hdl.e_theta20])
start=struct(...
    'alfa0',[str2num(get(hdl.e_alfa10,'string')) ...
        str2num(get(hdl.e_alfa20,'string'))],...
    'theta0',[str2num(get(hdl.e_theta10,'string'))... 
        str2num(get(hdl.e_theta20,'string'))],...
    'czas',[0 0]...
    )
end
if any (h==[hdl.r_Kv hdl.r_Kf ...
            hdl.r_f1 hdl.r_f2 hdl.r_k ...
            hdl.r_gamma hdl.r_beta hdl.r_da ...
            hdl.r_thetaH hdl.r_delta1 hdl.r_delta2])
    set([hdl.r_Kv hdl.r_Kf ...
         hdl.r_f1 hdl.r_f2 hdl.r_k ...
         hdl.r_gamma hdl.r_beta hdl.r_da ...
         hdl.r_thetaH hdl.r_delta1 hdl.r_delta2],'value',0.0)
    set(h,'value',1.0)
    zmiana_par=get(h,'string')
end